[package]
name = "lanred-dev/echo"
description = "A Roblox audio system."
version = "0.2.6"
registry = "https://github.com/UpliftGames/wally-index"
authors = ["Lanred"]
realm = "shared"
license = "MIT"
include = ["default.project.json", "src", "src/**", "LICENSE", "wally.toml", "Packages", "Packages/**"]
exclude = ["**"]

[dependencies]
Signal = "sleitnick/signal@2.0.1"